name: Run Data Assertions
  
on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage duckdb
      - name: Test with pytest
        run: |
          coverage run --source=. -m pytest -v tests && coverage report -m
